// User Property Actions
export const FETCH_USER_PROPERTIES_REQUEST = 'FETCH_USER_PROPERTIES_REQUEST';
export const FETCH_USER_PROPERTIES_SUCCESS = 'FETCH_USER_PROPERTIES_SUCCESS';
export const FETCH_USER_PROPERTIES_FAILURE = 'FETCH_USER_PROPERTIES_FAILURE';

export const FETCH_USER_PROPERTY_DETAILS_REQUEST = 'FETCH_USER_PROPERTY_DETAILS_REQUEST';
export const FETCH_USER_PROPERTY_DETAILS_SUCCESS = 'FETCH_USER_PROPERTY_DETAILS_SUCCESS';
export const FETCH_USER_PROPERTY_DETAILS_FAILURE = 'FETCH_USER_PROPERTY_DETAILS_FAILURE';

export const FILTER_USER_PROPERTIES = 'FILTER_USER_PROPERTIES';
export const SORT_USER_PROPERTIES = 'SORT_USER_PROPERTIES';

export const SAVE_PROPERTY_REQUEST = 'SAVE_PROPERTY_REQUEST';
export const SAVE_PROPERTY_SUCCESS = 'SAVE_PROPERTY_SUCCESS';
export const SAVE_PROPERTY_FAILURE = 'SAVE_PROPERTY_FAILURE';

export const UNSAVE_PROPERTY_REQUEST = 'UNSAVE_PROPERTY_REQUEST';
export const UNSAVE_PROPERTY_SUCCESS = 'UNSAVE_PROPERTY_SUCCESS';
export const UNSAVE_PROPERTY_FAILURE = 'UNSAVE_PROPERTY_FAILURE';

export const FETCH_SAVED_PROPERTIES_REQUEST = 'FETCH_SAVED_PROPERTIES_REQUEST';
export const FETCH_SAVED_PROPERTIES_SUCCESS = 'FETCH_SAVED_PROPERTIES_SUCCESS';
export const FETCH_SAVED_PROPERTIES_FAILURE = 'FETCH_SAVED_PROPERTIES_FAILURE';

export const CLEAR_USER_PROPERTY_ERROR = 'CLEAR_USER_PROPERTY_ERROR';
export const RESET_USER_PROPERTY_STATE = 'RESET_USER_PROPERTY_STATE';

export const CLIENT_CONTACT_REQUEST = 'CLIENT_CONTACT_REQUEST';
export const CLIENT_CONTACT_SUCCESS = 'CLIENT_CONTACT_SUCCESS';
export const CLIENT_CONTACT_FAILURE = 'CLIENT_CONTACT_FAILURE';
export const CLIENT_CONTACT_RESET = 'CLIENT_CONTACT_RESET';